GET http://localhost:8000/Weixin/getListOfAnswer
Accept: application/json

###
POST http://localhost:8000/Weixin/getUserRecord
Content-Type: application/x-www-form-urlencoded

id=1

###

POST http://localhost:8000/Weixin/getQuestion
Content-Type: application/x-www-form-urlencoded

num=10

###