POST http://localhost:80/Weixin/dmentReunion
Content-Type: application/x-www-form-urlencoded

openid=3

###

POST http://localhost:80/Weixin/Reunion
Content-Type: application/x-www-form-urlencoded

openid=10

###